version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  # Web App 1
  web1:
    container_name: web1
    build:
      context: ./web1
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  # Web App 2
  web2:
    container_name: web2
    build:
      context: ./web2
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  # Web Server 1
  server1:
    image: nginx:latest
    container_name: server1
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - web1
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # Web Server 2
  server2:
    image: nginx:latest
    container_name: server2
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - web2
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # Database
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - app-network

  # Database Manager (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    ports:
      - "8080:80"
    networks:
      - app-network
