version: "3"
services:
  # Web server
  server1:
    image: nginx:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - web1
    volumes:
      - ./web/1:/var/www/html

  server2:
    image: nginx:latest
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - web2
    volumes:
      - ./web/2:/var/www/html

  #Web App
  web1:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Resources/welcome-server1.blade.php:/var/www/html/resources/views/welcome.blade.php
      - ./web/1:/var/www/html

  web2:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./Resources/welcome-server2.blade.php:/var/www/html/resources/views/welcome.blade.php
      - ./web/2:/var/www/html

  #Database
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=uerPwd
      - POSTGRES_ROOT_PASSWORD=RootPwd
      - POSTGRES_DB=TPFinal
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data

  #Database Manager
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: psql
      PMA_USER: user
      PMA_PASSWORD: userPwd
    ports:
      - "80:80"

volumes:
  psql-data: